evening

diff --git a/n2n-status b/n2n-status
--- a/n2n-status
+++ b/n2n-status
@@ -14,15 +14,15 @@ then echo "edge process (`edge_pid`) is running"
 else echo "edge process is not running"; exit 1 ; fi
 
 if ping_gateway ;
-then echo "we can ping the gateway" \
+then echo "we can ping the gateway" 
 else echo "we can not ping the gateway" ; exit 1 ; fi
 
 echo -n "default routing for packets is via `default_route`"
 if [ `default_route` == $N2N_GATEWAY ] ;
-then echo ", i.e. the n2n gateway" \
-else echo ", i.e. not the n2n gateway" ; fi
+then echo ", the n2n gateway"
+else echo ", not the n2n gateway" ; fi
 
 if ping_ok 88.88.88.88 ; 
-then echo "Can see internet." 
-else echo "Cannot see internet." ; exit 1 ; fi
+then echo "we can see internet." 
+else echo "we cannot see internet." ; exit 1 ; fi
 
